<a href="https://colab.research.google.com/github/kanchan745/NumPy-Basics/blob/main/NumPy_Basics_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#speed high numpy and take less memory ,easy math operation ,large amount of data
#numpy array is a special type of list
temperatures = np.array([32.5,85.4,56.2])
average = np.mean(temperatures)
print(average)

58.03333333333334


In [2]:
#array : collection of no./values which can be store together in an organize manner
#tpes 1d ,2d ,3d ,multidimensional _array

numpy_array = [1,2,4,5]
print(numpy_array)

[1, 2, 4, 5]
[1, 2, 4, 5]


**1 Dimensional array**

one dimensional array it is simply a list of  no. that stores in a single row

In [6]:
ar_1d = np.array([10,20,30,40,50])
print(ar_1d)

[10 20 30 40 50]


**2 Dimensional array**

Two dimensional array : rows + columns

In [8]:
arr_2d = np.array([[1,2,3],[4,5,6],[5,5,8]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [5 5 8]]


**Multi-dimensional array**

A array that have multi dimension means 2d ,3d ,4d... use in Ai, Dl,MRI SCAN, 3D MODELLING, or we can say it has multiple layer of storage data, matrix-2d array

In [10]:
matrix = np.array([[2,4,6],[8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


# Creating arrays from python lists

In [11]:
arr = np.array([10,20,50])
print(arr)

[10 20 50]


**2nd Method with Default Values ....**

for which numpy provide built in function which is 0's function : use for future values
syntax -> np.zeros(shape)

In [14]:
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


**for 1's values** ones (shape)

In [19]:
ones_array = np.ones((2,3))#tuple form
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


**For specific values : full function** synatax: (shapes,value)

In [18]:
filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


# Sequences of numbers in numpy function : arange function (), syntax : arange(start,stop,step)

In [20]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


# creating identity matrix

It is a square matrix with ones on the diagonal and zeroes else where
# eye(size)

In [21]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
